import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/shared/navBar/navBar";

const tiktokSans = localFont({
  src: "../public/TikTok/TikTokSans-VF-v4-RC.otf",
  variable: "--font-tiktok-sans",
  display: "swap",
});




export const metadata: Metadata = {
  title: "Coodera",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tiktokSans.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
